/*
 * Created on 27 Nov 2016 ( Time 22:49:54 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package com.heroku.ra.repository;

import com.heroku.ra.entities.ActivitySubcategoryC ;

import org.springframework.data.repository.PagingAndSortingRepository;



/**
 * Spring JPA Repository for ActivitySubcategoryC
 * 
 * @author Telosys Tools Generator
 *
 */
public interface ActivitySubcategoryCRepository extends PagingAndSortingRepository<ActivitySubcategoryC, Integer> {
		ActivitySubcategoryC findBySfid(String sfid);


}