/*
 * Created on 27 Nov 2016 ( Time 22:49:54 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package com.heroku.ra.repository;

import com.heroku.ra.entities.Contact ;

import org.springframework.data.repository.PagingAndSortingRepository;



/**
 * Spring JPA Repository for Contact
 * 
 * @author Telosys Tools Generator
 *
 */
public interface ContactRepository extends PagingAndSortingRepository<Contact, Integer> {
		Contact findBySfid(String sfid);


}