/*
 * Created on 2 Dec 2016 ( Time 21:46:15 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package com.heroku.ra.repository;

import com.heroku.ra.entities.PropertyC ;

import org.springframework.data.repository.PagingAndSortingRepository;



/**
 * Spring JPA Repository for PropertyC
 * 
 * @author Telosys Tools Generator
 *
 */
public interface PropertyCRepository extends PagingAndSortingRepository<PropertyC, Integer> {
		PropertyC findBySfid(String sfid);


}