/*
 * Created on 27 Nov 2016 ( Time 22:49:54 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package com.heroku.ra.repository;

import com.heroku.ra.entities.ResortActivityC ;

import org.springframework.data.repository.PagingAndSortingRepository;



/**
 * Spring JPA Repository for ResortActivityC
 * 
 * @author Telosys Tools Generator
 *
 */
public interface ResortActivityCRepository extends PagingAndSortingRepository<ResortActivityC, Integer> {
		ResortActivityC findBySfid(String sfid);


}