/*
 * Created on 2 Dec 2016 ( Time 21:46:15 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package com.heroku.ra.repository;

import java.util.List;

import org.springframework.data.repository.PagingAndSortingRepository;

import com.heroku.ra.entities.SignupC ;



/**
 * Spring JPA Repository for SignupC
 * 
 * @author Telosys Tools Generator
 *
 */
public interface SignupCRepository extends PagingAndSortingRepository<SignupC, Integer> {
		SignupC findBySfid(String sfid);
		List<SignupC> findByContactC(String contact);

}