/*
 * Created on 5 Dec 2016 ( Time 11:51:40 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.heroku.ra.entities;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "guest_stay__c"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="guest_stay__c", schema="salesforce" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="GuestStayC.countAll", query="SELECT COUNT(x) FROM GuestStayC x" )
} )
public class GuestStayC implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="sfid", length=18)
    private String     sfid         ;

    @Column(name="number_of_guests__c")
    private Double     numberOfGuestsC ;

    @Column(name="name", length=80)
    private String     name         ;

    @Temporal(TemporalType.DATE)
    @Column(name="end_stay__c")
    private Date       endStayC     ;

    @Column(name="_hc_lastop", length=32)
    private String     hcLastop     ;

    @Column(name="property__c", length=18)
    private String     propertyC    ;

    @Column(name="isdeleted")
    private Boolean    isdeleted    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="systemmodstamp")
    private Date       systemmodstamp ;

    @Column(name="_hc_err", length=2147483647)
    private String     hcErr        ;

    @Temporal(TemporalType.DATE)
    @Column(name="begin_stay__c")
    private Date       beginStayC   ;

    @Column(name="guest__c", length=18)
    private String     guestC       ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createddate")
    private Date       createddate  ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public GuestStayC()
    {
		super();
    }

    public GuestStayC update(GuestStayC a) {
		this.id = a.id;
        this.sfid = a.sfid;
        this.numberOfGuestsC = a.numberOfGuestsC;
        this.name = a.name;
        this.endStayC = a.endStayC;
        this.hcLastop = a.hcLastop;
        this.propertyC = a.propertyC;
        this.isdeleted = a.isdeleted;
        this.systemmodstamp = a.systemmodstamp;
        this.hcErr = a.hcErr;
        this.beginStayC = a.beginStayC;
        this.guestC = a.guestC;
        this.createddate = a.createddate;



		return a;
	}

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id )
    {
        this.id = id ;
    }
    public Integer getId()
    {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : sfid ( varchar ) 
    public void setSfid( String sfid )
    {
        this.sfid = sfid;
    }
    public String getSfid()
    {
        return this.sfid;
    }

    //--- DATABASE MAPPING : number_of_guests__c ( float8 ) 
    public void setNumberOfGuestsC( Double numberOfGuestsC )
    {
        this.numberOfGuestsC = numberOfGuestsC;
    }
    public Double getNumberOfGuestsC()
    {
        return this.numberOfGuestsC;
    }

    //--- DATABASE MAPPING : name ( varchar ) 
    public void setName( String name )
    {
        this.name = name;
    }
    public String getName()
    {
        return this.name;
    }

    //--- DATABASE MAPPING : end_stay__c ( date ) 
    public void setEndStayC( Date endStayC )
    {
        this.endStayC = endStayC;
    }
    public Date getEndStayC()
    {
        return this.endStayC;
    }

    //--- DATABASE MAPPING : _hc_lastop ( varchar ) 
    public void setHcLastop( String hcLastop )
    {
        this.hcLastop = hcLastop;
    }
    public String getHcLastop()
    {
        return this.hcLastop;
    }

    //--- DATABASE MAPPING : property__c ( varchar ) 
    public void setPropertyC( String propertyC )
    {
        this.propertyC = propertyC;
    }
    public String getPropertyC()
    {
        return this.propertyC;
    }

    //--- DATABASE MAPPING : isdeleted ( bool ) 
    public void setIsdeleted( Boolean isdeleted )
    {
        this.isdeleted = isdeleted;
    }
    public Boolean getIsdeleted()
    {
        return this.isdeleted;
    }

    //--- DATABASE MAPPING : systemmodstamp ( timestamp ) 
    public void setSystemmodstamp( Date systemmodstamp )
    {
        this.systemmodstamp = systemmodstamp;
    }
    public Date getSystemmodstamp()
    {
        return this.systemmodstamp;
    }

    //--- DATABASE MAPPING : _hc_err ( text ) 
    public void setHcErr( String hcErr )
    {
        this.hcErr = hcErr;
    }
    public String getHcErr()
    {
        return this.hcErr;
    }

    //--- DATABASE MAPPING : begin_stay__c ( date ) 
    public void setBeginStayC( Date beginStayC )
    {
        this.beginStayC = beginStayC;
    }
    public Date getBeginStayC()
    {
        return this.beginStayC;
    }

    //--- DATABASE MAPPING : guest__c ( varchar ) 
    public void setGuestC( String guestC )
    {
        this.guestC = guestC;
    }
    public String getGuestC()
    {
        return this.guestC;
    }

    //--- DATABASE MAPPING : createddate ( timestamp ) 
    public void setCreateddate( Date createddate )
    {
        this.createddate = createddate;
    }
    public Date getCreateddate()
    {
        return this.createddate;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(sfid);
        sb.append("|");
        sb.append(numberOfGuestsC);
        sb.append("|");
        sb.append(name);
        sb.append("|");
        sb.append(endStayC);
        sb.append("|");
        sb.append(hcLastop);
        sb.append("|");
        sb.append(propertyC);
        sb.append("|");
        sb.append(isdeleted);
        sb.append("|");
        sb.append(systemmodstamp);
        sb.append("|");
        sb.append(hcErr);
        sb.append("|");
        sb.append(beginStayC);
        sb.append("|");
        sb.append(guestC);
        sb.append("|");
        sb.append(createddate);
        return sb.toString(); 
    } 

}