/*
 * Created on 3 Dec 2016 ( Time 12:00:39 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.heroku.ra.entities;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "signup__c"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="signup__c", schema="salesforce" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="SignupC.countAll", query="SELECT COUNT(x) FROM SignupC x" )
} )
public class SignupC implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="resort_activity__c", length=18)
    private String     resortActivityC ;

    @Column(name="_hc_lastop", length=32)
    private String     hcLastop     ;

    @Column(name="name", length=80)
    private String     name         ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lastmodifieddate")
    private Date       lastmodifieddate ;

    @Column(name="contact__c", length=18)
    private String     contactC     ;

    @Column(name="lastmodifiedbyid", length=18)
    private String     lastmodifiedbyid ;

    @Column(name="_hc_err", length=2147483647)
    private String     hcErr        ;

    @Column(name="createdbyid", length=18)
    private String     createdbyid  ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="systemmodstamp")
    private Date       systemmodstamp ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createddate")
    private Date       createddate  ;

    @Column(name="waitlisted__c")
    private Boolean    waitlistedC  ;

    @Column(name="contact_name__c", length=1300)
    private String     contactNameC ;

    @Column(name="sfid", length=18)
    private String     sfid         ;

    @Column(name="isdeleted")
    private Boolean    isdeleted    ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public SignupC()
    {
		super();
    }

        public SignupC update(SignupC a) {
		this.id = a.id;
        this.resortActivityC = a.resortActivityC;
        this.hcLastop = a.hcLastop;
        this.name = a.name;
        this.lastmodifieddate = a.lastmodifieddate;
        this.contactC = a.contactC;
        this.lastmodifiedbyid = a.lastmodifiedbyid;
        this.hcErr = a.hcErr;
        this.createdbyid = a.createdbyid;
        this.systemmodstamp = a.systemmodstamp;
        this.createddate = a.createddate;
        this.waitlistedC = a.waitlistedC;
        this.contactNameC = a.contactNameC;
        this.sfid = a.sfid;
        this.isdeleted = a.isdeleted;



		return a;
	}

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id )
    {
        this.id = id ;
    }
    public Integer getId()
    {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : resort_activity__c ( varchar ) 
    public void setResortActivityC( String resortActivityC )
    {
        this.resortActivityC = resortActivityC;
    }
    public String getResortActivityC()
    {
        return this.resortActivityC;
    }

    //--- DATABASE MAPPING : _hc_lastop ( varchar ) 
    public void setHcLastop( String hcLastop )
    {
        this.hcLastop = hcLastop;
    }
    public String getHcLastop()
    {
        return this.hcLastop;
    }

    //--- DATABASE MAPPING : name ( varchar ) 
    public void setName( String name )
    {
        this.name = name;
    }
    public String getName()
    {
        return this.name;
    }

    //--- DATABASE MAPPING : lastmodifieddate ( timestamp ) 
    public void setLastmodifieddate( Date lastmodifieddate )
    {
        this.lastmodifieddate = lastmodifieddate;
    }
    public Date getLastmodifieddate()
    {
        return this.lastmodifieddate;
    }

    //--- DATABASE MAPPING : contact__c ( varchar ) 
    public void setContactC( String contactC )
    {
        this.contactC = contactC;
    }
    public String getContactC()
    {
        return this.contactC;
    }

    //--- DATABASE MAPPING : lastmodifiedbyid ( varchar ) 
    public void setLastmodifiedbyid( String lastmodifiedbyid )
    {
        this.lastmodifiedbyid = lastmodifiedbyid;
    }
    public String getLastmodifiedbyid()
    {
        return this.lastmodifiedbyid;
    }

    //--- DATABASE MAPPING : _hc_err ( text ) 
    public void setHcErr( String hcErr )
    {
        this.hcErr = hcErr;
    }
    public String getHcErr()
    {
        return this.hcErr;
    }

    //--- DATABASE MAPPING : createdbyid ( varchar ) 
    public void setCreatedbyid( String createdbyid )
    {
        this.createdbyid = createdbyid;
    }
    public String getCreatedbyid()
    {
        return this.createdbyid;
    }

    //--- DATABASE MAPPING : systemmodstamp ( timestamp ) 
    public void setSystemmodstamp( Date systemmodstamp )
    {
        this.systemmodstamp = systemmodstamp;
    }
    public Date getSystemmodstamp()
    {
        return this.systemmodstamp;
    }

    //--- DATABASE MAPPING : createddate ( timestamp ) 
    public void setCreateddate( Date createddate )
    {
        this.createddate = createddate;
    }
    public Date getCreateddate()
    {
        return this.createddate;
    }

    //--- DATABASE MAPPING : waitlisted__c ( bool ) 
    public void setWaitlistedC( Boolean waitlistedC )
    {
        this.waitlistedC = waitlistedC;
    }
    public Boolean getWaitlistedC()
    {
        return this.waitlistedC;
    }

    //--- DATABASE MAPPING : contact_name__c ( varchar ) 
    public void setContactNameC( String contactNameC )
    {
        this.contactNameC = contactNameC;
    }
    public String getContactNameC()
    {
        return this.contactNameC;
    }

    //--- DATABASE MAPPING : sfid ( varchar ) 
    public void setSfid( String sfid )
    {
        this.sfid = sfid;
    }
    public String getSfid()
    {
        return this.sfid;
    }

    //--- DATABASE MAPPING : isdeleted ( bool ) 
    public void setIsdeleted( Boolean isdeleted )
    {
        this.isdeleted = isdeleted;
    }
    public Boolean getIsdeleted()
    {
        return this.isdeleted;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(resortActivityC);
        sb.append("|");
        sb.append(hcLastop);
        sb.append("|");
        sb.append(name);
        sb.append("|");
        sb.append(lastmodifieddate);
        sb.append("|");
        sb.append(contactC);
        sb.append("|");
        sb.append(lastmodifiedbyid);
        sb.append("|");
        sb.append(hcErr);
        sb.append("|");
        sb.append(createdbyid);
        sb.append("|");
        sb.append(systemmodstamp);
        sb.append("|");
        sb.append(createddate);
        sb.append("|");
        sb.append(waitlistedC);
        sb.append("|");
        sb.append(contactNameC);
        sb.append("|");
        sb.append(sfid);
        sb.append("|");
        sb.append(isdeleted);
        return sb.toString(); 
    } 

}