/*
 * Created on 2 Dec 2016 ( Time 21:46:15 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package com.heroku.ra.services;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.heroku.ra.entities.ResortActivityC;
import com.heroku.ra.exceptions.ResortActivityCNotFoundException;
import com.heroku.ra.repository.ResortActivityCRepository;

@Service
@Transactional(rollbackFor=ResortActivityCNotFoundException.class)
public class ResortActivityCService 
{
	private static Logger logger = LoggerFactory.getLogger(ResortActivityCService.class);
	
	@Autowired
	private ResortActivityCRepository resortactivitycRepository;
		
	/*
	 * READ methods
	 */
	public Page<ResortActivityC> findAll(int page, int count) {
		
		if (logger.isDebugEnabled())
			logger.debug("ResortActivityCService -> findAll ResortActivityCs");
		
		return resortactivitycRepository.findAll(new PageRequest(page, count));
	}

	public Iterable<ResortActivityC> findAll() {
		
		if (logger.isDebugEnabled())
			logger.debug("ResortActivityCService -> findAll ResortActivityCs");
		
		return resortactivitycRepository.findAll();
	}

	public ResortActivityC findBySfid(String resortactivityc){
		if (logger.isDebugEnabled())
			logger.debug("Retrieving ResortActivityC with sfid:" + resortactivityc);
		
		return resortactivitycRepository.findBySfid(resortactivityc);
		
	}

	public ResortActivityC get(int id) {
		if (logger.isDebugEnabled())
			logger.debug("Retrieving ResortActivityC with id:" + id);
		
		ResortActivityC elementToGet = resortactivitycRepository.findOne(id);
		
		if (elementToGet == null)
			throw new ResortActivityCNotFoundException(id);
		
		return elementToGet;
	}

	public ResortActivityC create(ResortActivityC resortactivityc) {

		if (logger.isDebugEnabled())
			logger.debug("ResortActivityCService -> create:" + resortactivityc);
			
		return resortactivitycRepository.save(resortactivityc);
	}

	public ResortActivityC update(ResortActivityC resortactivityc) {
		
		if (logger.isDebugEnabled())
			logger.debug("ResortActivityCService -> create:" + resortactivityc);

		ResortActivityC elementToUpdate = resortactivitycRepository.findOne(resortactivityc.getId());
		
		if (elementToUpdate == null)
			throw new ResortActivityCNotFoundException(resortactivityc.getName());
		
		elementToUpdate.update(resortactivityc);
		resortactivitycRepository.save(elementToUpdate);
		
		return elementToUpdate;
	}

	public ResortActivityC delete(int id) {
		if (logger.isDebugEnabled())
			logger.debug("ResortActivityCService -> delete:" + id);

		ResortActivityC elementToDelete = get(id);
		
		if (elementToDelete == null)
			throw new ResortActivityCNotFoundException(id);
		
		resortactivitycRepository.delete(elementToDelete);

		return elementToDelete;
	}

	public List<ResortActivityC> getToday(){
		Date today = new Date();
		Date startOfToday;
		Date endOfToday;
		try {
//			Calendar c = Calendar.getInstance(); 
//			c.setTime(today); 
//			c.add(Calendar.DATE, 1);
//			after = c.getTime();
			
//			SimpleDateFormat todayFormat = new SimpleDateFormat("yyyy/MM/dd hh:mma");
			SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
			SimpleDateFormat afterFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
	
//			System.out.println("TODAY [] - " + todayFormat.format(today));
//			System.out.println("AFTER [] - " + afterFormat.format(after));
	
			startOfToday = afterFormat.parse(dateFormat.format(today) + " 00:00:00");
			endOfToday = afterFormat.parse(dateFormat.format(today) + " 23:59:59");
			
			System.out.println("START OF TODAY ---- " + afterFormat.format(startOfToday));
			System.out.println("END OF TODAY ---- " + afterFormat.format(endOfToday));
			
			return resortactivitycRepository.findByActivityStartCBefore(endOfToday);
		} catch (ParseException e) {
			e.printStackTrace();
		}
		return null;
	}
	
	public List<ResortActivityC> getUpcoming(){
		Date today = new Date();
		Date startOfDay;
		Date endOfDay;
		Date tomorrow;
		try {
			Calendar c = Calendar.getInstance(); 
			c.setTime(today); 
			c.add(Calendar.DATE, 1);
			tomorrow = c.getTime();
			
			SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
			SimpleDateFormat afterFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
	
			startOfDay = afterFormat.parse(dateFormat.format(tomorrow) + " 00:00:00");
			endOfDay = afterFormat.parse(dateFormat.format(tomorrow) + " 23:59:59");
			
			System.out.println("START OF TOMORROW ---- " + afterFormat.format(startOfDay));
			System.out.println("END OF TOMORROW ---- " + afterFormat.format(endOfDay));
			
			return resortactivitycRepository.findByActivityStartCAfter(startOfDay);
		} catch (ParseException e) {
			e.printStackTrace();
		}
		return null;
	}
}

