/*
 * Created on 27 Nov 2016 ( Time 22:49:54 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package com.heroku.ra.exceptions;

public class ActivityCategoryCNotFoundException extends RuntimeException {

	private static final long serialVersionUID = -1L;

	public ActivityCategoryCNotFoundException(Integer id) {
		super("ActivityCategoryC not found with id: " + id.toString());
	}

	public ActivityCategoryCNotFoundException(String activitycategoryc) {
		super("ActivityCategoryC " + activitycategoryc + " not found!");
	}
}
