/*
 * Created on 2 Dec 2016 ( Time 21:46:14 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package com.heroku.ra.exceptions;

public class ContactNotFoundException extends RuntimeException {

	private static final long serialVersionUID = -1L;

	public ContactNotFoundException(Integer id) {
		super("Contact not found with id: " + id.toString());
	}

	public ContactNotFoundException(String contact) {
		super("Contact " + contact + " not found!");
	}
}
