/*
 * Created on 5 Dec 2016 ( Time 11:51:40 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package com.heroku.ra.exceptions;

public class GuestStayCNotFoundException extends RuntimeException {

	private static final long serialVersionUID = -1L;

	public GuestStayCNotFoundException(Integer id) {
		super("GuestStayC not found with id: " + id.toString());
	}

	public GuestStayCNotFoundException(String gueststayc) {
		super("GuestStayC " + gueststayc + " not found!");
	}
}
