/*
 * Created on 2 Dec 2016 ( Time 21:46:15 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package com.heroku.ra.exceptions;

public class PropertyCNotFoundException extends RuntimeException {

	private static final long serialVersionUID = -1L;

	public PropertyCNotFoundException(Integer id) {
		super("PropertyC not found with id: " + id.toString());
	}

	public PropertyCNotFoundException(String propertyc) {
		super("PropertyC " + propertyc + " not found!");
	}
}
