/*
 * Created on 2 Dec 2016 ( Time 16:47:10 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package com.heroku.ra.exceptions;

public class SignupCNotFoundException extends RuntimeException {

	private static final long serialVersionUID = -1L;

	public SignupCNotFoundException(Integer id) {
		super("SignupC not found with id: " + id.toString());
	}

	public SignupCNotFoundException(String signupc) {
		super("SignupC " + signupc + " not found!");
	}
}
