/*
 * Created on 27 Nov 2016 ( Time 22:49:54 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package com.heroku.ra.controllers;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.heroku.ra.model.ResponseMessage;
import com.heroku.ra.entities.ActivityCategoryC;
import com.heroku.ra.services.ActivityCategoryCService;

@Controller
@RequestMapping(value="/api/v1/activitycategoryc")
public class ActivityCategoryCRestController {
	
	private static Logger logger = LoggerFactory.getLogger(ActivityCategoryCRestController.class);
	
	@Autowired
	private ActivityCategoryCService activitycategorycService;
		
	/*
	 * READ METHODS
	 */

	@RequestMapping(value="", method=RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE, consumes = MediaType.APPLICATION_JSON_VALUE)
	@ResponseBody
	public ResponseMessage getAll() {

		if (logger.isDebugEnabled())
			logger.debug("ActivityCategoryCService -> getPage");
		
		ResponseMessage responseMessage = new ResponseMessage();
		try {
			responseMessage.setData(activitycategorycService.findAll());
		} catch (Exception e) {
			logger.error("ActivityCategoryCController -> getAll", e);
			responseMessage.setError(-1, "Unable to get page for ActivityCategoryC: " + e.getMessage());
		}
		return responseMessage;
	}

	@RequestMapping(value="/page", method=RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE, consumes = MediaType.APPLICATION_JSON_VALUE)
	@ResponseBody
	public ResponseMessage getPage(@RequestParam int page, @RequestParam int records) {

		if (logger.isDebugEnabled())
			logger.debug("ActivityCategoryCService -> getPage");
		
		ResponseMessage responseMessage = new ResponseMessage();
		try {
			responseMessage.setData(activitycategorycService.findAll(page, records));
		} catch (Exception e) {
			logger.error("ActivityCategoryCController -> getPage", e);
			responseMessage.setError(-1, "Unable to get page for ActivityCategoryC: " + e.getMessage());
		}
		return responseMessage;
		
	}


//	@RequestMapping(value="/count", method=RequestMethod.GET,
//			produces = MediaType.APPLICATION_JSON_VALUE, consumes = MediaType.APPLICATION_JSON_VALUE)
//	@ResponseBody
//	public ResponseMessage getCount() {
//
//		if (logger.isDebugEnabled())
//			logger.debug("ActivityCategoryCService -> getAll");
//		
//		ResponseMessage responseMessage = new ResponseMessage();
//		try {
//			responseMessage.setData(activitycategorycService.count());
//		} catch (Exception e) {
//			logger.error("ActivityCategoryCController -> getAll", e);
//			responseMessage.setError(-1, "Unable to get all ActivityCategoryC: " + e.getMessage());
//		}
//		return responseMessage;
//		
//	}

//	@RequestMapping(value="/page", method=RequestMethod.GET,
//			produces = MediaType.APPLICATION_JSON_VALUE, consumes = MediaType.APPLICATION_JSON_VALUE)
//	@ResponseBody
//	public ResponseMessage getPage(@RequestParam int page,@RequestParam int size) {
//
//		if (logger.isDebugEnabled())
//			logger.debug("ActivityCategoryCService -> getPage(" + page + "," + size + ")");
//		
//		ResponseMessage responseMessage = new ResponseMessage();
//		try {
//			responseMessage.setData(activitycategorycService.getPage(page, size));
//		} catch (Exception e) {
//			logger.error("ActivityCategoryCController -> getAll", e);
//			responseMessage.setError(-1, "Unable to get all ActivityCategoryC: " + e.getMessage());
//		}
//		return responseMessage;
//		
//	}
	
//	@RequestMapping(value="/elements", method=RequestMethod.GET,
//			produces = MediaType.APPLICATION_JSON_VALUE, consumes = MediaType.APPLICATION_JSON_VALUE)
//	@ResponseBody
//	public ResponseMessage getDropDownElements() {
//
//		if (logger.isDebugEnabled())
//			logger.debug("ActivityCategoryCService -> getDropDownElements");
//		
//		ResponseMessage responseMessage = new ResponseMessage();
//		try {
//			responseMessage.setData(activitycategorycService.getDropDownValues());
//		} catch (Exception e) {
//			logger.error("ActivityCategoryCController -> getDropDownElements", e);
//			responseMessage.setError(-1, "Unable to getDropDownElements for ActivityCategoryC: " + e.getMessage());
//		}
//		return responseMessage;
//		
//	}

	@RequestMapping(value="/{id}", method=RequestMethod.GET,
			produces = {MediaType.APPLICATION_JSON_VALUE, MediaType.APPLICATION_XML_VALUE}, consumes = {MediaType.APPLICATION_JSON_VALUE, MediaType.APPLICATION_XML_VALUE})
	@ResponseBody
	public ResponseMessage getOne(@PathVariable Integer id) {
		if (logger.isDebugEnabled())
			logger.debug("ActivityCategoryCService -> getOne(" + id + ")");
		ResponseMessage responseMessage = new ResponseMessage();
		
		try {
			responseMessage.setData(activitycategorycService.get(id));
		} catch (Exception e) {
			logger.error("ActivityCategoryCController -> create", e);
			responseMessage.setError(-1,
					"Unable to create ActivityCategoryC: " + id + ",Error:"  + e.getMessage());
		}
		
		return responseMessage;
	}

	
	/*
	 * DML Methods
	 */
	@RequestMapping(value = "/create", method = RequestMethod.POST, produces = MediaType.APPLICATION_JSON_VALUE, consumes = MediaType.APPLICATION_JSON_VALUE)
	@ResponseBody
	public ResponseMessage create(@RequestBody ActivityCategoryC element) {

		if (logger.isDebugEnabled())
			logger.debug("ActivityCategoryCService -> create:" + element);

		ResponseMessage responseMessage = new ResponseMessage();
		
		try {
			responseMessage.setData(activitycategorycService.create(element));
		} catch (Exception e) {
			logger.error("ActivityCategoryCController -> create", e);
			responseMessage.setError(-1,
					"Unable to create ActivityCategoryC: " + element + ",Error:"  + e.getMessage());
		}
		
		return responseMessage;
	}

	@RequestMapping(value = "/edit/{id}", method = RequestMethod.PUT, produces = MediaType.APPLICATION_JSON_VALUE, consumes = MediaType.APPLICATION_JSON_VALUE)
	@ResponseBody
	public ResponseMessage edit(@PathVariable Integer id, @RequestBody ActivityCategoryC element) {
		if (logger.isDebugEnabled())
			logger.debug("ActivityCategoryCService -> edit(" + id + "):" + element);

		ResponseMessage responseMessage = new ResponseMessage();
		
		try {
			element.setId(id);
			responseMessage.setData(activitycategorycService.create(element));
		} catch (Exception e) {
			logger.error("ActivityCategoryCController -> edit", e);
			responseMessage.setError(-1,
					"Unable to edit ActivityCategoryC: " + element + ",Error:" + e.getMessage());
		}
		
		return responseMessage;
	}

	@RequestMapping(value="/delete/{id}", method=RequestMethod.DELETE, 
			produces = MediaType.APPLICATION_JSON_VALUE, consumes = MediaType.APPLICATION_JSON_VALUE)
	@ResponseBody
	public ResponseMessage delete(@PathVariable Integer id) {

		if (logger.isDebugEnabled())
			logger.debug("ActivityCategoryCService -> delete(" + id + ")");

		ResponseMessage responseMessage = new ResponseMessage();
		try {
			activitycategorycService.delete(id);
		} catch (Exception e) {
			logger.error("ActivityCategoryCController -> delete", e);
			responseMessage.setError(-1, "Unable to delete ActivityCategoryC: " + id + ",Error:"  + e.getMessage());
		}
		return responseMessage;
	}
	
}

