/*
 * Created on 2 Dec 2016 ( Time 21:46:14 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package com.heroku.ra.controllers;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import javax.servlet.http.HttpServletResponse;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ExceptionHandler;

import com.heroku.ra.model.ResponseMessage;
import com.heroku.ra.dto.User;
import com.heroku.ra.dto.UserLoginDTO;
import com.heroku.ra.entities.Contact;
import com.heroku.ra.services.ContactService;

@Controller
@RequestMapping(value="/api/v1/contact")
public class ContactRestController {
	
	private static Logger logger = LoggerFactory.getLogger(ContactRestController.class);
	
	@Autowired
	private ContactService contactService;
		
	/*
	 * READ METHODS
	 */

	@RequestMapping(value="", method=RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE, consumes = MediaType.APPLICATION_JSON_VALUE)
	@ResponseBody
	public ResponseMessage getAll() {

		if (logger.isDebugEnabled())
			logger.debug("ContactService -> getPage");
		
		ResponseMessage responseMessage = new ResponseMessage();
		try {
			responseMessage.setData(contactService.findAll());
		} catch (Exception e) {
			logger.error("ContactController -> getAll", e);
			responseMessage.setError(-1, "Unable to get page for Contact: " + e.getMessage());
		}
		return responseMessage;
	}

	@RequestMapping(value="/page", method=RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE, consumes = MediaType.APPLICATION_JSON_VALUE)
	@ResponseBody
	public ResponseMessage getPage(@RequestParam int page, @RequestParam int records) {

		if (logger.isDebugEnabled())
			logger.debug("ContactService -> getPage");
		
		ResponseMessage responseMessage = new ResponseMessage();
		try {
			responseMessage.setData(contactService.findAll(page, records));
		} catch (Exception e) {
			logger.error("ContactController -> getPage", e);
			responseMessage.setError(-1, "Unable to get page for Contact: " + e.getMessage());
		}
		return responseMessage;
		
	}

	@RequestMapping(value="/login", method=RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE, consumes = MediaType.APPLICATION_JSON_VALUE)
	@ResponseBody
	public ResponseMessage login(@RequestParam String email, @RequestParam String password) {

		if (logger.isDebugEnabled())
			logger.debug("ContactService -> login");
		
		ResponseMessage responseMessage = new ResponseMessage();
		try {
			UserLoginDTO u = new UserLoginDTO(email, password);
			responseMessage.setData(contactService.doLogin(u));
		} catch (Exception e) {
			logger.error("ContactController -> getPage", e);
			responseMessage.setError(-1, "Unable to login user: " + email + " - " + e.getMessage());
		}
		return responseMessage;
		
	}

	@RequestMapping(value = "/login", method = RequestMethod.POST, produces = MediaType.APPLICATION_JSON_VALUE, consumes = MediaType.APPLICATION_JSON_VALUE)
	@ResponseBody
	public ResponseMessage loginPost(@RequestBody UserLoginDTO u) {
	
	if (logger.isDebugEnabled())
		logger.debug("ContactService -> login");
	
	ResponseMessage responseMessage = new ResponseMessage();
	try {
		responseMessage.setData(contactService.doLogin(u));
	} catch (Exception e) {
		logger.error("ContactController -> getPage", e);
		responseMessage.setError(-1, "Unable to login user: " + u.getEmail() + " - " + e.getMessage());
	}
	return responseMessage;
	
}


	@RequestMapping(value="/{id}", method=RequestMethod.GET,
			produces = {MediaType.APPLICATION_JSON_VALUE, MediaType.APPLICATION_XML_VALUE}, consumes = {MediaType.APPLICATION_JSON_VALUE, MediaType.APPLICATION_XML_VALUE})
	@ResponseBody
	public ResponseMessage getOne(@PathVariable Integer id) {
		if (logger.isDebugEnabled())
			logger.debug("ContactService -> getOne(" + id + ")");
		ResponseMessage responseMessage = new ResponseMessage();
		
		try {
			responseMessage.setData(contactService.get(id));
		} catch (Exception e) {
			logger.error("ContactController -> create", e);
			responseMessage.setError(-1,
					"Unable to create Contact: " + id + ",Error:"  + e.getMessage());
		}
		
		return responseMessage;
	}	
	
	/*
	 * DML Methods
	 */
	@RequestMapping(value = "/signup", method = RequestMethod.POST, produces = MediaType.APPLICATION_JSON_VALUE, consumes = MediaType.APPLICATION_JSON_VALUE)
	@ResponseBody
	public ResponseMessage signup(@RequestBody User element) {

		if (logger.isDebugEnabled())
			logger.debug("ContactService -> signup:" + element);

		ResponseMessage responseMessage = new ResponseMessage();
		
		Contact c = element.toContact();
		
		try {
			responseMessage.setData(contactService.create(c));
		} catch (Exception e) {
			logger.error("ContactController -> create", e);
			responseMessage.setError(-1,
					"Unable to create Contact: " + element.getEmail() + ",Error:"  + e.getMessage());
			//e.printStackTrace();
		}
		
		return responseMessage;
	}
	
	@RequestMapping(value = "/edit/{id}", method = RequestMethod.PUT, produces = MediaType.APPLICATION_JSON_VALUE, consumes = MediaType.APPLICATION_JSON_VALUE)
	@ResponseBody
	public ResponseMessage edit(@PathVariable Integer id, @RequestBody Contact element) {
		if (logger.isDebugEnabled())
			logger.debug("ContactService -> edit(" + id + "):" + element);

		ResponseMessage responseMessage = new ResponseMessage();
		
		try {
			element.setId(id);
			responseMessage.setData(contactService.create(element));
		} catch (Exception e) {
			logger.error("ContactController -> edit", e);
			responseMessage.setError(-1,
					"Unable to edit Contact: " + element + ",Error:" + e.getMessage());
		}
		
		return responseMessage;
	}

	@RequestMapping(value="/delete/{id}", method=RequestMethod.DELETE, 
			produces = MediaType.APPLICATION_JSON_VALUE, consumes = MediaType.APPLICATION_JSON_VALUE)
	@ResponseBody
	public ResponseMessage delete(@PathVariable Integer id) {

		if (logger.isDebugEnabled())
			logger.debug("ContactService -> delete(" + id + ")");

		ResponseMessage responseMessage = new ResponseMessage();
		try {
			contactService.delete(id);
		} catch (Exception e) {
			logger.error("ContactController -> delete", e);
			responseMessage.setError(-1, "Unable to delete Contact: " + id + ",Error:"  + e.getMessage());
		}
		return responseMessage;
	}
	
	@ExceptionHandler(Exception.class)
	public @ResponseBody
	String handleException(Exception e, HttpServletResponse response) {
	    response.setStatus(HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
	    return e.getMessage();
	}

}

