/*
 * Created on 2 Dec 2016 ( Time 21:46:15 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package com.heroku.ra.controllers;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import javax.servlet.http.HttpServletResponse;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ExceptionHandler;

import com.heroku.ra.model.ResponseMessage;
import com.heroku.ra.entities.ResortActivityC;
import com.heroku.ra.services.ResortActivityCService;

@Controller
@RequestMapping(value="/api/v1/resortactivities")
public class ResortActivityCRestController {
	
	private static Logger logger = LoggerFactory.getLogger(ResortActivityCRestController.class);
	
	@Autowired
	private ResortActivityCService resortactivitycService;
		
	/*
	 * READ METHODS
	 */

	@RequestMapping(value="", method=RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
	@ResponseBody
	public ResponseMessage getAll() {

		if (logger.isDebugEnabled())
			logger.debug("ResortActivityCService -> getPage");
		
		ResponseMessage responseMessage = new ResponseMessage();
		try {
			responseMessage.setData(resortactivitycService.findAll());
		} catch (Exception e) {
			logger.error("ResortActivityCController -> getAll", e);
			responseMessage.setError(-1, "Unable to get page for ResortActivityC: " + e.getMessage());
		}
		return responseMessage;
	}

	@RequestMapping(value="/page", method=RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
	@ResponseBody
	public ResponseMessage getPage(@RequestParam int page, @RequestParam int records) {

		if (logger.isDebugEnabled())
			logger.debug("ResortActivityCService -> getPage");
		
		ResponseMessage responseMessage = new ResponseMessage();
		try {
			responseMessage.setData(resortactivitycService.findAll(page, records));
		} catch (Exception e) {
			logger.error("ResortActivityCController -> getPage", e);
			responseMessage.setError(-1, "Unable to get page for ResortActivityC: " + e.getMessage());
		}
		return responseMessage;
		
	}

	@RequestMapping(value="/{id}", method=RequestMethod.GET,
			produces = {MediaType.APPLICATION_JSON_VALUE, MediaType.APPLICATION_XML_VALUE}, consumes = {MediaType.APPLICATION_JSON_VALUE, MediaType.APPLICATION_XML_VALUE})
	@ResponseBody
	public ResponseMessage getOne(@PathVariable Integer id) {
		if (logger.isDebugEnabled())
			logger.debug("ResortActivityCService -> getOne(" + id + ")");
		ResponseMessage responseMessage = new ResponseMessage();
		
		try {
			responseMessage.setData(resortactivitycService.get(id));
		} catch (Exception e) {
			logger.error("ResortActivityCController -> create", e);
			responseMessage.setError(-1,
					"Unable to create ResortActivityC: " + id + ",Error:"  + e.getMessage());
		}
		
		return responseMessage;
	}

	
	/*
	 * DML Methods
	 */
	@RequestMapping(value = "/create", method = RequestMethod.POST, produces = MediaType.APPLICATION_JSON_VALUE, consumes = MediaType.APPLICATION_JSON_VALUE)
	@ResponseBody
	public ResponseMessage create(@RequestBody ResortActivityC element) {

		if (logger.isDebugEnabled())
			logger.debug("ResortActivityCService -> create:" + element);

		ResponseMessage responseMessage = new ResponseMessage();
		
		try {
			responseMessage.setData(resortactivitycService.create(element));
		} catch (Exception e) {
			logger.error("ResortActivityCController -> create", e);
			responseMessage.setError(-1,
					"Unable to create ResortActivityC: " + element + ",Error:"  + e.getMessage());
		}
		
		return responseMessage;
	}

	@RequestMapping(value = "/edit/{id}", method = RequestMethod.PUT, produces = MediaType.APPLICATION_JSON_VALUE, consumes = MediaType.APPLICATION_JSON_VALUE)
	@ResponseBody
	public ResponseMessage edit(@PathVariable Integer id, @RequestBody ResortActivityC element) {
		if (logger.isDebugEnabled())
			logger.debug("ResortActivityCService -> edit(" + id + "):" + element);

		ResponseMessage responseMessage = new ResponseMessage();
		
		try {
			element.setId(id);
			responseMessage.setData(resortactivitycService.create(element));
		} catch (Exception e) {
			logger.error("ResortActivityCController -> edit", e);
			responseMessage.setError(-1,
					"Unable to edit ResortActivityC: " + element + ",Error:" + e.getMessage());
		}
		
		return responseMessage;
	}

	@RequestMapping(value="/delete/{id}", method=RequestMethod.DELETE, 
			produces = MediaType.APPLICATION_JSON_VALUE, consumes = MediaType.APPLICATION_JSON_VALUE)
	@ResponseBody
	public ResponseMessage delete(@PathVariable Integer id) {

		if (logger.isDebugEnabled())
			logger.debug("ResortActivityCService -> delete(" + id + ")");

		ResponseMessage responseMessage = new ResponseMessage();
		try {
			resortactivitycService.delete(id);
		} catch (Exception e) {
			logger.error("ResortActivityCController -> delete", e);
			responseMessage.setError(-1, "Unable to delete ResortActivityC: " + id + ",Error:"  + e.getMessage());
		}
		return responseMessage;
	}
	
	@ExceptionHandler(Exception.class)
	public @ResponseBody
	String handleException(Exception e, HttpServletResponse response) {
	    response.setStatus(HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
	    return e.getMessage();
	}

}

